# Generated by Django 2.0.8 on 2018-09-30 20:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SingleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', wagtail.core.fields.RichTextField()),
                ('ans1', models.CharField(blank=True, max_length=255, null=True)),
                ('ans2', models.CharField(blank=True, max_length=255, null=True)),
                ('ans3', models.CharField(blank=True, max_length=255, null=True)),
                ('ans4', models.CharField(blank=True, max_length=255, null=True)),
                ('ans5', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_ans', models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], max_length=1)),
                ('category', models.CharField(choices=[('logic', 'Logic'), ('math', 'Math'), ('pattern', 'Pattern'), ('spacial', 'Spacial')], max_length=25)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_question', to='assessment.SingleQuestion'),
        ),
    ]
