# Generated by Django 2.0.8 on 2018-09-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='question',
        ),
        migrations.AlterField(
            model_name='singlequestion',
            name='correct_ans',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
