# Generated by Django 2.0.8 on 2018-09-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20180930_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlequestion',
            name='category',
            field=models.CharField(choices=[('logic', 'Logic'), ('math', 'Math'), ('pattern', 'Pattern'), ('spacial', 'Spacial'), ('language', 'Language'), ('reasoning', 'Reasoning')], max_length=25),
        ),
    ]
