# Generated by Django 2.0.8 on 2018-09-27 20:38

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homepage_content',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_heading',
            field=models.TextField(default=''),
        ),
    ]
