# Generated by Django 2.0.8 on 2018-09-27 23:11

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0005_auto_20180927_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, default='', null=True)),
                ('last_name', models.TextField(blank=True, default='', null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('birthday', models.DateField()),
                ('validation_key', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignupPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
