# Generated by Django 2.0.8 on 2018-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_verifyemailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='validation_datetime',
            field=models.DateTimeField(default='2018-09-30 15:15:15'),
            preserve_default=False,
        ),
    ]
